### ISSUE TITLE
Crash generating mad scientist house

### ISSUE THREAD

**Issue by Shahelion** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.7.10#1]
Brief explanation of problem:
For some reason, it tries to generate a mad scientist house in a few of the cave dimensions from DeeperCaves. After the crash, I can load back in without further crashing, until the next attempt somewhere else. Is there a way I could restrict these to only the Overworld?

Crash report:
https://gist.github.com/Shahelion/ffa7aba7c97ac77701969f8b72742e1a

MatterOverdrive version:
0.4.2

Minecraft version:
1.7.10

**Comment by infiniteblock** [comment]
Should be fixed in the first community version of 1.7.10 just uploading to curseforge now

**Comment by Shahelion** [comment]
Wonderful, thank you. I will let you know if it persists for some reason.

**Comment by infiniteblock** [comment]
for some reason cf has requested manual review of the 1.7.10 version, i have put it on modrinth now
https://modrinth.com/mod/moce/versions?g=1.7.10

**Comment by Shahelion** [comment]
Using newest version (from the issue with the config) it still crashes, but might be a slightly different problem now.

https://gist.github.com/Shahelion/ed4b373960b6ba6e3958928320c4c604

**Comment by infiniteblock** [comment]
https://cdn.discordapp.com/attachments/1209064386950471700/1224215524939137075/MatterOverdrive-1.7.10-0.4.4.jar?ex=661cae8d&is=660a398d&hm=01276e5bc807dc19f3ce73c726ef317458d0081249360bcb4b16a9a5c5e1d9f9&

here's a new build hopefully fix's it damn crazy worlds haha i added the mod to the dev environment and didn't get a crash so hopefully

**Comment by Shahelion** [comment]
Looks like that did it! I flew around and saw several villages generating on the map, but no more crash. I did also notice that it seems to be generating the exact same village every time, this mod is weird idk anymore. I can't even get up on top of the world to verify it visually, but the map shows the same thing in each world.

Thank you for your patience. c:
